# Generated by Django 5.0.4 on 2024-07-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_blogger_alter_react_blogger'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=450)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogger',
        ),
    ]
