# Generated by Django 5.0.4 on 2024-07-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_title'),
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogger',
            field=models.ManyToManyField(to='blogger.blogger'),
        ),
        migrations.AlterField(
            model_name='react',
            name='blogger',
            field=models.ManyToManyField(to='blogger.blogger'),
        ),
    ]
